### ISSUE TITLE
Feature: IDEA: trigger ktfmt check on attempted commit

### ISSUE THREAD

**Issue by isXander** [facebook/ktfmt#255]
It would be cool if ktfmt executed a check when a user attempts to commit to VCS (maybe as a warning).

Or even better, runs the formatter itself when you attempt to commit.

I have countless times committed my code to then fail on CI because I forget to run ktfmt.

**Comment by ColtonIdle** [comment]
You can write a git precommit hook to just run ktfmt before you can even commit locally.

You could probably copy it fromt this ktlin gradle plugin repo: https://github.com/JLLeitschuh/ktlint-gradle#additional-helper-tasks

**Comment by cortinico** [comment]
If you use `ktfmt-gradle` there is a section about using ktfmt as a pre-commit hook here:https://github.com/cortinico/ktfmt-gradle#using-with-a-pre-commit-hook-

**Comment by JavierSegoviaCordoba** [comment]
If you are using the IDEA plugin it will reformat the code of all changed files if you have the checkbox selected.

**Comment by 0x26res** [comment]
For [pre-commit](https://pre-commit.com/) users, I've recently added support for ktfmt in the `language-formatter-pre-commit-hooks`. It doesn't require gradle, you just need python and java installed in your dev environment.

See the MR: https://github.com/macisamuele/language-formatters-pre-commit-hooks/pull/196

Here's a sample `.pre-commit-config.yaml`
```
repos:
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.12.0
    hooks:
      - id: pretty-format-kotlin
        files: "^.*.(kts|kt)$"
        name: ktfmt
        args: [--ktfmt, --ktfmt-style=google, --autofix]
```

Thanks @macisamuele for helping setting it up.
